import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { forwardRef } from 'react';
export const ProvisionalReceipt = forwardRef(({ tableId, items, total, cashier, orderId }, ref) => {
    const formatMoney = (amount) => amount.toLocaleString('vi-VN') + ' đ';
    return (_jsxs("div", { ref: ref, className: "provisional-receipt", style: {
            padding: '20px',
            width: '300px', // Khổ giấy 80mm khoảng ~300px
            fontFamily: 'monospace, sans-serif',
            color: '#000',
            background: '#fff',
            margin: '0 auto'
        }, children: [_jsxs("div", { style: { textAlign: 'center', marginBottom: '16px' }, children: [_jsx("h2", { style: { margin: '0 0 5px 0', fontSize: '20px' }, children: "NH\u00C0 H\u00C0NG ABC" }), _jsx("p", { style: { margin: '0', fontSize: '12px' }, children: "123 \u0110\u01B0\u1EDDng XYZ, Qu\u1EADn 1, TP.HCM" }), _jsx("p", { style: { margin: '0', fontSize: '12px' }, children: "\u0110T: 0123.456.789" }), _jsx("h3", { style: { margin: '15px 0 5px 0', fontSize: '18px', borderTop: '1px dashed #000', paddingTop: '10px' }, children: "H\u00D3A \u0110\u01A0N T\u1EA0M T\u00CDNH" }), _jsxs("p", { style: { margin: '0', fontSize: '14px', fontWeight: 'bold' }, children: ["B\u00E0n: ", tableId] })] }), _jsxs("div", { style: { fontSize: '12px', marginBottom: '10px' }, children: [_jsxs("p", { style: { margin: '2px 0' }, children: ["M\u00E3 \u0111\u01A1n: #", orderId || 'N/A'] }), _jsxs("p", { style: { margin: '2px 0' }, children: ["Ng\u00E0y: ", new Date().toLocaleString('vi-VN')] }), _jsxs("p", { style: { margin: '2px 0' }, children: ["Thu ng\u00E2n: ", cashier] })] }), _jsxs("table", { style: { width: '100%', fontSize: '12px', borderCollapse: 'collapse', marginBottom: '10px' }, children: [_jsx("thead", { children: _jsxs("tr", { style: { borderBottom: '1px dashed #000' }, children: [_jsx("th", { style: { textAlign: 'left', paddingBottom: '5px' }, children: "M\u00F3n" }), _jsx("th", { style: { textAlign: 'center', paddingBottom: '5px' }, children: "SL" }), _jsx("th", { style: { textAlign: 'right', paddingBottom: '5px' }, children: "TT" })] }) }), _jsx("tbody", { children: items.map((item, idx) => (_jsxs("tr", { children: [_jsxs("td", { style: { paddingTop: '5px', paddingBottom: '5px' }, children: [item.name, item.note && _jsxs("div", { style: { fontSize: '10px', fontStyle: 'italic' }, children: ["(", item.note, ")"] })] }), _jsx("td", { style: { textAlign: 'center', paddingTop: '5px', paddingBottom: '5px' }, children: item.quantity }), _jsx("td", { style: { textAlign: 'right', paddingTop: '5px', paddingBottom: '5px' }, children: formatMoney(item.price * item.quantity) })] }, idx))) })] }), _jsxs("div", { style: { borderTop: '1px dashed #000', paddingTop: '10px', marginTop: '10px', fontSize: '16px', fontWeight: 'bold', display: 'flex', justifyContent: 'space-between' }, children: [_jsx("span", { children: "T\u1ED4NG C\u1ED8NG:" }), _jsx("span", { children: formatMoney(total) })] }), _jsxs("div", { style: { textAlign: 'center', marginTop: '20px', fontSize: '12px', borderTop: '1px dashed #000', paddingTop: '10px' }, children: [_jsx("p", { style: { margin: '0' }, children: "(H\u00F3a \u0111\u01A1n t\u1EA1m t\u00EDnh - Ch\u01B0a c\u00F3 gi\u00E1 tr\u1ECB thanh to\u00E1n thu\u1EBF)" }), _jsx("p", { style: { margin: '5px 0' }, children: "Xin c\u1EA3m \u01A1n qu\u00FD kh\u00E1ch!" })] })] }));
});
